# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
import numpy
from numpy.typing import NDArray
from typing import Optional


@dataclasses.dataclass()
class Item:
    id: int
    embedding: Optional[NDArray[numpy.float32]]
